apiVersion: apps/v1
kind: Deployment
metadata: { }
spec:
  replicas: 1
  selector:
    matchLabels:
      { }
  template:
    metadata: { }
    spec:
      containers:
        - name: apicurio-studio-app
          image: quay.io/apicurio/apicurio-studio:latest-snapshot
          env: [ ]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /apis/studio/v1/system/info
              port: 8080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /apis/studio/v1/system/info
              port: 8080
              scheme: HTTP
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1000Mi
