apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels

labels:
  app: apicurio-studio-operator
  app.kubernetes.io/name: apicurio-studio-operator
  app.kubernetes.io/version: PLACEHOLDER_VERSION
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: apicurio-studio

fieldSpecs:
  - path: metadata/labels
    create: true
  - path: spec/template/metadata/labels
    create: true
