# DO NOT COMMIT AUTOMATIC MODIFICATIONS TO THIS FILE
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - role.yaml
  - role-binding.yaml

commonLabels:
  app: apicurio-studio-operator
  app.kubernetes.io/name: apicurio-studio-operator
  app.kubernetes.io/version: PLACEHOLDER_VERSION
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: apicurio-studio
