apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apicurio-studio-operator-rolebinding
  namespace: PLACEHOLDER_NAMESPACE

subjects:
  - kind: ServiceAccount
    name: apicurio-studio-operator
    namespace: PLACEHOLDER_NAMESPACE

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apicurio-studio-operator-role
