# Note: Do not forget to update deploy/rbac/cluster/kustomization.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apicurio-studio-operator-role
  namespace: PLACEHOLDER_NAMESPACE

rules:

  - apiGroups:
      - studio.apicur.io
    resources:
      - apicuriostudios
      - apicuriostudios/status
    verbs:
      - '*'

  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'

  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - '*'

  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - '*'

  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - '*'

  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get

  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get

  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - "*"
